name: Archive tester
on:
  workflow_dispatch:
jobs:
  run-purchase:
    runs-on: ubuntu-latest
    steps:
      - uses: rich-automation/lotto-archive-action@latest
        with:
          numbersArray: "[[2,4,5,12,32,45],[9,23,24,29,31,35],[2,15,16,23,28,40],[3,8,13,16,27,29],[14,17,19,29,31,34]]"
          round: "1166"
          token: ${{ secrets.GITHUB_TOKEN }}
          debug: true
